Notlarim/Notlarim.WebUI/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Notlarim.Business.Abstract;
using Notlarim.WebUI.Models;
using System.Security.Claims;
using Notlarim.Entities;
using Newtonsoft.Json;
using System.Text;

namespace Notlarim.WebUI.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private IMemberService _memberService;
        public LoginController(IMemberService memberService)
        {
            _memberService = memberService;
        }

        #region Web Api İşlemleri
        public IActionResult Login()
        {
            return View();
        }
        public async Task<IActionResult> LoginFromRestApi(MemberModel loginModel)
        {

            using (var httpClient = new HttpClient())
            {
                var apiUrl = "https://localhost:7034/api/logins/Login";
                var jsonContent = new StringContent(JsonConvert.SerializeObject(loginModel), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(apiUrl, jsonContent))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var loginUser = _memberService.LoginUser(loginModel.Email, loginModel.Password);
                        if (loginUser.UserStatu == "Admin")
                        {
                            var claims = new List<Claim>
                            {
                                  new Claim(ClaimTypes.Email,loginUser.Email),
                            };

                            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            var authProperties = new AuthenticationProperties();
                            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                            HttpContext.Session.SetString("usermail", loginUser.Email);
                            HttpContext.Session.SetString("usernamesurname", loginUser.Name + " " + loginUser.SurName);
                            HttpContext.Session.SetString("username", loginUser.Name);
                            HttpContext.Session.SetString("usersurname", loginUser.SurName);
                            HttpContext.Session.SetString("userphoto", loginUser.MemberImageUrl);
                            HttpContext.Session.SetInt32("userid", loginUser.MemberId);
                            HttpContext.Session.SetString("userphonenumber", loginUser.PhoneNumber);
                            HttpContext.Session.SetString("usergender", loginUser.Gender);
                            HttpContext.Session.SetString("useruniversity", loginUser.University);
                            HttpContext.Session.SetString("userdeparment", loginUser.Department);
                            HttpContext.Session.SetString("useruserstatu", loginUser.UserStatu);

                            return RedirectToAction("Index", "Admin");
                        }
                        else if (loginUser.UserStatu == "User")
                        {
                            var claims = new List<Claim>
                            {
                                  new Claim(ClaimTypes.Email,loginUser.Email),
                            };

                            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            var authProperties = new AuthenticationProperties();
                            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                            HttpContext.Session.SetString("usermail", loginUser.Email);
                            HttpContext.Session.SetString("usernamesurname", loginUser.Name + " " + loginUser.SurName);
                            HttpContext.Session.SetString("username", loginUser.Name);
                            HttpContext.Session.SetString("usersurname", loginUser.SurName);
                            HttpContext.Session.SetString("userphoto", loginUser.MemberImageUrl);
                            HttpContext.Session.SetInt32("userid", loginUser.MemberId);
                            HttpContext.Session.SetString("userphonenumber", loginUser.PhoneNumber);
                            HttpContext.Session.SetString("usergender", loginUser.Gender);
                            HttpContext.Session.SetString("useruniversity", loginUser.University);
                            HttpContext.Session.SetString("userdeparment", loginUser.Department);
                            HttpContext.Session.SetString("useruserstatu", loginUser.UserStatu);
                            return RedirectToAction("GetNoteFromRestApi", "Home");
                        }
                    }
                }
                ViewBag.Error = "Mail adresiniz veya Şifreniz hatalı";
                return View("Login", loginModel);
            }
        }

        public IActionResult MemberAdd()
        {
            return View();
        }
        public async Task<IActionResult> MemberAddFromRestApi(MemberModel model)
        {
            bool userCheck = _memberService.UserCheckMail(model.Email);

            if (userCheck)
            {
                ViewBag.Error = "Bu e-posta adresi zaten kullanımda.";
                return View("MemberAdd", model);
            }

            using (var httpClient = new HttpClient())
            {
                if (model.Gender == "kadın")
                {
                    model.MemberImageUrl = "bayan-user.png";
                    model.UserStatu = "User";
                }
                else
                {
                    model.MemberImageUrl = "erkek-user.jpeg";
                    model.UserStatu = "User";
                }
                var apiUrl = "https://localhost:7034/api/logins/MemberAdd";
                var jsonContent = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(apiUrl, jsonContent))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Login));
                    }
                }

            }
            ViewBag.Error = "Bilinmeyen bir hata oluştu.";
            return View("MemberAdd", model);
        }
        #endregion

    }
}

Notlarim/Notlarim.WebUI/Controllers/NoteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Notlarim.Business.Abstract;
using Notlarim.Entities;
using Notlarim.WebUI.Models;

namespace Notlarim.WebUI.Controllers
{
    
    public class NoteController : Controller
    {
        private INoteService _noteService;
        private ICategoryService _categoryService;
        public NoteController(INoteService noteService, ICategoryService categoryService)
        {
            _noteService = noteService;
            _categoryService = categoryService;
    
        }

        #region Note Web Uı İşlemeleri
        //// Kullanıcıya ait noteları listeler
        //public async Task<IActionResult> NoteList(int userId)
        //{
        //    //var userId = HttpContext.Session.GetInt32("userıd");
        //    var noteList =await _noteService.UserNotes((int)userId);
        //    return View(noteList);
        //}

        [HttpGet]
        public async Task<IActionResult> NoteAdd()
        {
            var category = await _categoryService.GetAll();
            List<SelectListItem> categoryValues = (from c in category
                                                   select new SelectListItem
                                                   {
                                                       Text = c.CategoryName,
                                                       Value = c.CategoryId.ToString()
                                                   }).ToList();
            ViewBag.categories = categoryValues;
            return View();
        }
        [HttpPost]
        public IActionResult NoteAdd(NoteModel note, IFormFile file, IFormFile pdffile)
        {
            if (note != null)
            {
                var entity = new Note
                {
                    Title = note.Title,
                    Content = note.Content,
                    NoteImgUrl = file.FileName,
                    NotePdfUrl = pdffile.FileName,
                    CategoryId = note.CategoryId,
                    MemberId = note.MemberId,
                    IsApproved = false
                };
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\upload\\img", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                var pdfpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\upload\\pdf", pdffile.FileName);
                using (var stream = new FileStream(pdfpath, FileMode.Create))
                {
                    pdffile.CopyTo(stream);
                }
                _noteService.Add(entity);
                return RedirectToAction("NoteList");
            }
            return View(note);
        }
        [HttpGet]
        public async Task<IActionResult> NoteDetails(int noteId)
        {
            var category = await _categoryService.GetAll();
            List<SelectListItem> categoryValues = (from c in category
                                                   select new SelectListItem
                                                   {
                                                       Text = c.CategoryName,
                                                       Value = c.CategoryId.ToString()
                                                   }).ToList();
            ViewBag.categories = categoryValues;

            Note model = await _noteService.GetById(noteId);

            var entity = new NoteModel()
            {
                NoteId = noteId,
                Title = model.Title,
                Content = model.Content,
                NoteImgUrl = model.NoteImgUrl,
                NotePdfUrl = model.NotePdfUrl,
                CategoryId = model.CategoryId,
            };

            return View(entity);
        }
        [HttpPost]
        public async Task<IActionResult> NoteDetails(NoteModel note, IFormFile file, IFormFile pdffile)
        {
            var entity = await _noteService.GetById(note.NoteId);
            if (entity == null)
            {
                return NotFound();
            }
            else if (entity != null)
            {
                entity.Title = note.Title;
                entity.Content = note.Content;
                entity.CategoryId = note.CategoryId;
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\upload\\img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }
                    entity.NoteImgUrl = file.FileName;
                }
                else
                {
                    entity.NoteImgUrl = entity.NoteImgUrl;
                }
                
                if (pdffile != null)
                {
                    var pdfpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\upload\\pdf", pdffile.FileName);
                    using (var stream = new FileStream(pdfpath, FileMode.Create))
                    {
                        pdffile.CopyTo(stream);
                    }
                    entity.NotePdfUrl = pdffile.FileName;
                }
                else
                {
                    entity.NotePdfUrl = entity.NotePdfUrl;
                }
                _noteService.Update(entity);
                return RedirectToAction("NoteList");
            }
            return View(note);
        }
        [HttpPost]
        public async Task<IActionResult> NoteDelete(int noteId)
        {
            Note note = await _noteService.GetById(noteId);
            if (note == null)
            {
                return NotFound();
            }
            _noteService.Delete(note);
            return RedirectToAction("NoteList");
        }
        #endregion

        #region Not Web APİ İşleşeri
        // Kullanıcıya ait noteları listeler
        public async Task<IActionResult> GetNoteListFromRestApi(int userId)
        {
            var noteList = new List<Note>();
            using (var httpClint = new HttpClient())
            {
                using (var response = await httpClint.GetAsync($"https://localhost:7034/api/notes/GetProducts/{userId}"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var apiResponse = await response.Content.ReadAsStringAsync();
                        noteList = JsonConvert.DeserializeObject<List<Note>>(apiResponse);
                    }
                }
            }
            return View(noteList);
        }
        #endregion
    }
}

Notlarim/Notlarim.WebUI/Views/Shared/_Admin.cshtml
@{
    // Kullanıcının giriş yapmış olup olmadığını kontrol ediyoruz
    bool isLoggedIn = Context.Session.GetString("usermail") != null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notlarim.WebUI</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Notlarim.WebUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/dashboard.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-light flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" style="text-transform:uppercase" asp-action="Index">Ders Notlarım</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                @if (isLoggedIn)
                {
                    <div class="d-flex justify-content-between">
                        <a class="nav-link text-dark ">
                            <img src="~/upload/img/@Context.Session.GetString("userphoto")" class="yuvarlak"> @Context.Session.GetString("username")
                        </a>
                       
                        <a asp-controller="Account" asp-action="LogOut" class="nav-link text-dark mt-1 ml-3">
                            <img src="~/upload/img/enter.png" width="15" height="15"> Çıkış Yap
                        </a>
                    </div>
                }
                else
                {
                    <div class="justify-content-end ml-auto">
                        <a asp-controller="Login" asp-action="Login" class="text-dark"><img src="~/upload/img/enter.png" width="15" height="15" >Giriş Yap</a>
                    </div>

                }
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="Index">
                                <span><i class=" fas fa-sharp fa-regular fa-house" style="color: #d82c4e;"></i></span>
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="NoteList">
                                <span ><i class="fas fa-sticky-note" style="color: #d82c4e;"></i></span>
                                Notlar
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="MemberList">
                                <span><i class="fas fa-users" style="color: #d82c4e;"></i></span>
                                Üyeler
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="CategoryList">
                                <span><i class="fas fa-th-list" style="color: #d82c4e;"></i></span>
                                Kategoriler
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="MailList">
                                <span><i class="fas fa-envelope" style="color: #d82c4e;"></i></span>
                              
                                Mesajlar
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                @RenderBody()
            </main>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <script src="dashboard.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Notlarim/Notlarim.WebUI/Views/Shared/_Layout.cshtml
@{
    // Kullanıcının giriş yapmış olup olmadığını kontrol ediyoruz
    bool isLoggedIn = Context.Session.GetString("usermail") != null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Notlarim.WebUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-4">
                <img src="~/upload/img/logo.png" width="100" height="75">
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-sm menu  site-navbar">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item  menu-link">
                    <a class="nav-link menu-a" asp-controller="Home" asp-action="GetNoteFromRestApi">Ana Sayfa</a>
                </li>
                <li class="nav-item  menu-link">
                    <a class="nav-link menu-a" asp-controller="Home" asp-action="GetCategoriesAndNotesFromRestApi">Üniversite Ders Notları</a>
                </li>
                <li class="nav-item  menu-link">
                    <a class="nav-link menu-a" asp-controller="Home" asp-action="About">Hakkımızda</a>
                </li>
                <li class="nav-item  menu-link">
                    <a class="nav-link menu-a" asp-controller="Home" asp-action="Contact">İletişim</a>
                </li>
            </ul>

            <form method="post" asp-action="SearchFromRestApi" class="d-flex justify-content-center input-group w-auto ml-auto">
                <input type="search" class="form-control rounded" placeholder="Search" id="search" name="search" aria-label="Search"
                       aria-describedby="search-addon" />
                <span class="input-group-text border-0" id="search-addon">
                    <i class="fas fa-search"></i>
                </span>
            </form>
            @if (isLoggedIn)
            {
                <div class="justify-content-end ml-auto">
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle text-dark" role="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="~/upload/img/@Context.Session.GetString("userphoto")" class="yuvarlak"> @Context.Session.GetString("usernamesurname")
                        </a>
                        <span class="caret"></span>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <a class="dropdown-item text-dark" asp-controller="Account" asp-action="GetUserProfileFromRestApi" asp-route-userId="@Context.Session.GetInt32("userid")">Profil</a>
                            <a class="dropdown-item text-dark" asp-controller="Note" asp-action="GetNoteListFromRestApi" asp-route-userId="@Context.Session.GetInt32("userid")">Notlarım</a>
                            <a class="dropdown-item text-dark" asp-controller="Account" asp-action="LogOut">Çıkış Yap</a>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="justify-content-end ml-auto">
                    <a asp-controller="Login" asp-action="Login" class="text-dark mt-3"><img src="~/upload/img/enter.png" width="15" height="15" class="mr-3">Giriş Yap</a>
                </div>

            }
        </div>
    </nav>





    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="container-fluid" style="background-color: #1c2331;">
        <div class="container">
            <footer class="text-lg-start text-white">
                <section class="container-fluid">
                    <div class="containertext-md-start pt-5 mt-5">
                        <div class="row mt-3">
                            <div class="col-md-4  mb-4">
                                <h6 class="text-uppercase fw-bold">Ders Notlarım</h6>
                                <hr class="mb-4 mt-0 d-inline-block mx-auto"
                                    style="width: 60px; background-color: #ffffff; height: 2px" />
                                <p style="color: silver;">
                                    Ders Notlarım ile cep telefonunuzdan, tabletinizden istediğiniz her yerden, internet bağlantı ihtiyacı olmadan tüm
                                    ders notlarınız her an yanınızda!
                                </p>
                            </div>
                            <div class="col-md-4  mb-4">
                                <h6 class="text-uppercase fw-bold">Hızlı Erişim</h6>
                                <hr class="mb-4 mt-0 d-inline-block mx-auto"
                                    style="width: 60px; background-color: #ffffff; height: 2px" />
                                <p>
                                    <a asp-controller="Home" asp-action="NoteList" style="color: silver;">Anasayfa</a>
                                </p>
                                <p>
                                    <a asp-controller="Home" asp-action="CategoriesAndNotes" style="color: silver;">Üniversite Ders Notları</a>
                                </p>
                                <p>
                                    <a asp-controller="Home" asp-action="About" style="color: silver;">Hakkımızda</a>
                                </p>
                                <p>
                                    <a asp-controller="Home" asp-action="Contact" style="color: silver;">İletişim</a>
                                </p>
                            </div>
                            <div class="col-md-4 mb-4">
                                <h6 class="text-uppercase fw-bold">Iletişim</h6>
                                <hr class="mb-4 mt-0 d-inline-block mx-auto"
                                    style="width: 60px; background-color: #ffffff; height: 2px" />
                                <p style="color: silver;"><i class="fa fa-home mr-3" style="color: #ffffff;"></i> Kadıköy / İstanbul</p>
                                <p style="color: silver;">
                                    <i class="fas fa-envelope mr-3" style="color: #ffffff;"></i>
                                    notlarim@gmail.com
                                </p>
                                <p style="color: silver;">
                                    <i class="fas fa-phone mr-3" style="color: #ffffff;"></i> +90 534 345 67 89
                                </p>
                            </div>
                        </div>
                    </div>
                </section>

                <section class="d-flex justify-content-between p-4" style="background-color: rgba(0, 0, 0, 0.2)">
                    <div class="me-5">
                        <span>
                            © 2023 Copyright
                            <a class="text-white" href="index.html">notlarim.com // All rights reserved.</a>
                        </span>
                    </div>

                </section>
            </footer>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Notlarim/Notlarim.WebUI/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notlarim.WebUI</title>
   @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Notlarim.WebUI.styles.css" asp-append-version="true" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>