Notlarim/Notlarim.WebUI/ViewComponents/Admin/CategoryCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Notlarim.Business.Abstract;

namespace Notlarim.WebUI.ViewComponents.Admin
{
    public class CategoryCountViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryCountViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _categoryService.GetAll();
            return View(model);
        }
    }
}

Notlarim/Notlarim.WebUI/ViewComponents/Admin/MailCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Notlarim.Business.Abstract;

namespace Notlarim.WebUI.ViewComponents.Admin
{
    public class MailCountViewComponent: ViewComponent
    {
        private IMessageService _messageService;
        public MailCountViewComponent(IMessageService messageService)
        {
            _messageService = messageService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _messageService.GetAll();
            return View(model);
        }
    }
}

Notlarim/Notlarim.WebUI/ViewComponents/Admin/MemberCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Notlarim.Business.Abstract;

namespace Notlarim.WebUI.ViewComponents.Admin
{
    public class MemberCountViewComponent:ViewComponent
    {
        private IMemberService _memberService;
        public MemberCountViewComponent(IMemberService memberService)
        {
            _memberService = memberService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var memberCount = await _memberService.GetAll();
            return View(memberCount);
        }
    }
}

Notlarim/Notlarim.WebUI/ViewComponents/Admin/NoteCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Notlarim.Business.Abstract;

namespace Notlarim.WebUI.ViewComponents.Admin
{
    public class NoteCountViewComponent:ViewComponent
    {
        private INoteService _noteService;
        public NoteCountViewComponent(INoteService noteService)
        {
            _noteService = noteService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notes = await _noteService.GetAll();
            return View(notes);
        }
    }
}

Notlarim/Notlarim.WebUI/Views/Admin/CategoryAdd.cshtml
@model CategoryModel
@{
    ViewData["Title"] = "CategoryAdd";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Kategory Ekle</h4>
            <p class="card-description">
                Lütfen Tüm Alanları Doldurunuz
            </p>
            <form asp-action="CategoryAdd" method="post">
                <div class="form-group">
                    <label asp-for="CategoryName" class="control-label"></label>
                    <input asp-for="CategoryName" class="form-control" placeholder="Kategori"
                           required="Gerekli" data-validation-required-message="Lütfen Başlık Giriniz" />
                </div>
                <button type="submit" class="btn btn-primary mr-2">Ekle</button>
                <button class="btn btn-light">İptal</button>
            </form>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/CategoryDetails.cshtml
@model CategoryModel

@{
    ViewData["Title"] = "CategoryDetails";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Kategory Düzenle</h4>
            <p class="card-description">
            </p>
            <form asp-action="CategoryDetails" method="post">
                <input name="CategoryId" type="hidden" class="form-control" value="@Model.CategoryId">
                <div class="form-group">
                    <label asp-for="CategoryName" class="control-label"></label>
                    <input asp-for="CategoryName" class="form-control" placeholder="Kategori"
                           required="Gerekli" data-validation-required-message="Lütfen Başlık Giriniz" />
                </div>
                <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button class="btn btn-light">İptal</button>
            </form>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/CategoryList.cshtml
@model IEnumerable<Category>
@{
    ViewData["Title"] = "CategoryList";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<h1 class="m-5">Kategoriler</h1>



<div class="col-md-12">
    <a asp-controller="Admin" asp-action="CategoryAdd" class="btn btn-outline-primary">Kategori Ekle</a>
    <div class="table-responsive mt-5 ">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th>Kategori Id</th>
                    <th>Kategori Adı</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CategoryId</td>
                        <td>@item.CategoryName</td>
                        <td>
                            <a asp-controller="Admin" asp-action="CategoryDetails" asp-route-categoryId="@item.CategoryId" class="btn btn-outline-success">Detaylar</a>
                            <form asp-controller="Admin" asp-action="CategoryDelete" class="d-inline" method="post">
                                <input type="hidden" name="categoryId" value="@item.CategoryId">
                                <button class='btn btn-outline-danger'>Sil</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/Index.cshtml
@model List<Note>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="page-header mt-5">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <span></span>Genel Bakış <i class="mdi mdi-alert-circle-outline icon-sm text-warning align-middle"></i>
            </li>
        </ul>
    </nav>
</div>

<div class="row justify-content-center">
    <div class="col-md-4 col-xl-3">
        <div class="card bg-c-blue order-card">
            <div class="card-block">
                <h6 class="m-b-20"> <i class="fas fa-sticky-note fa-lg" style="color: #ffffff;"></i>&nbsp &nbsp Notlar</h6>
              
                <p style="margin-left:50px;" class="m-b-0">Toplam @await Component.InvokeAsync("NoteCount")</p>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-xl-3">
        <div class="card bg-c-green order-card">
            <div class="card-block">
                <h6 class="m-b-20"><i class="fas fa-check-circle fa-lg" style="color: #ffffff;"></i>&nbsp &nbsp Onaylı Notlar</h6>
             
                <p style="margin-left:50px;" class="m-b-0">Toplam @await Component.InvokeAsync("NoteIsApprovedCount")</p>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-xl-3">
        <div class="card bg-c-yellow order-card">
            <div class="card-block">
                <h6 class="m-b-20"><i class="fas fa-times-circle fa-lg" style="color: #ffffff;"></i>&nbsp &nbsp Onaylanmayan Notlar</h6>
                <p style="margin-left:50px;" class="m-b-0">Toplam @await Component.InvokeAsync("NoteIsNotApprovedCount")</p>
            </div>
        </div>
    </div>

</div>
<div class="row justify-content-center">
    <div class="col-md-4 col-xl-3">
        <div class="card bg-c-info order-card">
            <div class="card-block">
                <h6 class="m-b-20"><i class="fas fa-users" style="color: #ffffff;"></i>&nbsp &nbsp Üyeler</h6>
                <p style="margin-left:50px;" class="m-b-0">Toplam @await Component.InvokeAsync("MemberCount")</p>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-xl-3">
        <div class="card bg-c-pink order-card">
            <div class="card-block">
                <h6 class="m-b-20"><i class="fas fa-th-list fa-lg" style="color: #ffffff;"></i>&nbsp &nbsp Kategoriler</h6>
               
                <p style="margin-left:50px;" class="m-b-0">Toplam @await Component.InvokeAsync("CategoryCount")</p>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-xl-3">
        <div class="card bg-c-danger order-card">
            <div class="card-block">
                <h6 class="m-b-20"><i class="fas fa-envelope fa-lg" style="color: #ffffff;"></i>&nbsp &nbsp Mesajlar</h6>

                <p style="margin-left:50px;" class="m-b-0">Toplam @await Component.InvokeAsync("MailCount")</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Son 10 Blog</h4>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th> Resim </th>
                                <th> Baslık </th>
                                <th> Kategori </th>
                                <th> Yazar </th>
                                <th>Not Durum</th>
                                <th> Yayınlama Tarihi </th>
                                <th> Detaylar </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.OrderByDescending(b => b.NoteId).Take(10))
                            {
                                <tr>
                                    <td>
                                        <img src="~/upload/img/@item.NoteImgUrl" width="50" height="50" alt="" />
                                    </td>
                                    <td> @item.Title </td>
                                    <td> @item.Category.CategoryName </td>
                                    <td> @item.Member.Name @item.Member.SurName </td>
                                    <td>
                                        @if (item.IsApproved == true)
                                        {
                                            <span class="badge badge-success">Yayında</span>
                                        }
                                        else if (item.IsApproved == false)
                                        {
                                            <span class="badge badge-danger"> Yayında değil</span>
                                        }

                                    </td>
                                    <td> @item.CreatDate.ToString("MMM d, yyyyy") </td>
                                    <td> <a asp-controller="Admin" asp-action="NoteDetails" asp-route-noteId="@item.NoteId" class="btn btn-outline-success btn-fw">Detay</a> </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/MailList.cshtml
@using MyBlog.Entities.Concrete;
@model IEnumerable<Messages>
@{
    ViewData["Title"] = "MailList";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Mesajlar</h4>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th> İsim </th>
                                <th> Mail </th>
                                <th> Title </th>
                                <th> Konu </th>
                                <th> Mesaj Durum </th>
                                <th> Mesaj Tarihi </th>
                                <th> Detaylar </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td> @item.Email </td>
                                    <td> @item.Title </td>
                                    <td> @item.Message </td>
                                    <td>
                                        @if (item.MessageStatus == true)
                                        {
                                            <span class="badge badge-success">Cevaplandı</span>
                                        }
                                        else if (item.MessageStatus == false)
                                        {
                                            <span class="badge badge-danger"> Cevap Bekliyor</span>
                                        }

                                    </td>
                                    <td> @item.CreatDate.ToString("MMM d, yyyyy") </td>
                                    <td> <a asp-controller="Admin" asp-action="MailSend" asp-route-mailId="@item.MessagesId" class="btn btn-outline-success btn-fw">Detay</a> </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/MailSend.cshtml
@model MailRequest
@{
    ViewData["Title"] = "MailSend";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Mesaj Detay</h4>
                <form class="forms-sample">
                    <input type="hidden" name="MessagesId" value="@Model.MessagesId">
                    <div class="form-group">
                        <label>İsim</label>
                        <input asp-for=Name value="@Model.Name" type="text" class="form-control" readonly>
                    </div>
                    <div class="form-group">
                        <label>E-mail</label>
                        <input asp-for=Email value="@Model.Email" type="text" class="form-control" readonly>
                    </div>
                    <div class="form-group">
                        <label>Konu</label>
                        <input asp-for=Title value="@Model.Title" type="text" class="form-control" readonly>
                    </div>
                    <div class="form-group">
                        <label>Mesaj</label>
                        <textarea asp-for=Message value="@Model.Message" type="text" class="form-control" readonly></textarea>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Mesaj Gönder</h4>
                <form asp-controller="Admin" asp-action="MailSend" method="post" class="forms-sample">
                    <input type="hidden" name="MessagesId" value="@Model.MessagesId">
                    <div class="form-group">
                        <label>Alıcı Mail</label>
                        <input asp-for=@Model.Email value="@Model.Email" type="text" readonly class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Gönderen</label>
                        <input asp-for="AnswerName" value="@Context.Session.GetString("username")" type="text" class="form-control" readonly>
                    </div>
                    <div class="form-group">
                        <label>Konu</label>
                        <input asp-for="AnswerTitle" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Mesaj</label>
                        <textarea asp-for=AnswerMessage class="form-control"></textarea>
                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Mail Gönder</button>
                </form>
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/MemberDetails.cshtml
@model MemberStatuModel
@{
    ViewData["Title"] = "MemberDetails";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="row m-5">
    <div class="col-md-4">
        <div class="profile-img">
            <img src="~/upload/img/@Model.MemberImageUrl" width="250" height="250" alt="" />
        </div>
    </div>
    <div class="col-md-6">
        <div class="profile-head">
            <h5>
                @Model.Name @Model.SurName
            </h5>
            <h6>Okul</h6>
            <p>@Model.University</p>
            <h6>Bölüm</h6>
            <p>@Model.Department</p>
        </div>
    </div>

</div>
<div class="row">
    <div class="col-md-4">
        <div class="profile-work">
        </div>
    </div>
    <div class="col-md-8">
        <div class="tab-content profile-tab">
            <div class="tab-pane fade show active">
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="MemberId" class="font-weight-bold"></label>
                    </div>
                    <div class="col-md-6">
                        <p>@Model.MemberId</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="Name" class="font-weight-bold"></label>
                    </div>
                    <div class="col-md-6">
                        <p>@Model.Name</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="SurName" class="font-weight-bold"></label>
                    </div>
                    <div class="col-md-6">
                        <p>@Model.SurName</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="Email" class="font-weight-bold"></label>
                    </div>
                    <div class="col-md-6">
                        <p>@Model.Email</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="PhoneNumber" class="font-weight-bold">Phone</label>
                    </div>
                    <div class="col-md-6">
                        <p>@Model.PhoneNumber</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="Gender" class="font-weight-bold"></label>
                    </div>
                    <div class="col-md-6">
                        <p>@Model.Gender</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <form asp-controller="Admin" asp-action="MemberDetails" method="post" enctype="multipart/form-data" class="forms-sample">
                            <input name="MemberId" type="hidden" class="form-control" value="@Model.MemberId">
                            <div class="form-group">
                                <label asp-for="UserStatu"></label>
                                <select asp-for="UserStatu" value="@Model.UserStatu" class="form-control" required>
                                    <option value="User">Kullanıcı</option>
                                    <option value="Admin">Admin</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                            <button class="btn btn-light">İptal</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/MemberList.cshtml
@model IEnumerable<Member>
@{
    ViewData["Title"] = "MemberList";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1 class="m-5 mt-5">Üyeler</h1>

<div class="col-md-12">
    <div class="table-responsive mt-5 ">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th>Fotoğraf</th>
                    <th>İsim Soyisim</th>
                    <th>Email</th>
                    <th>Yükleme-Güncelleme Tarihi</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><img src="~/upload/img/@item.MemberImageUrl" width="50" height="" /></td>
                        <td>@item.Name @item.SurName</td>
                        <td>@item.Email</td>
                        <td>@item.CreatDate.ToString("dd.MM.yyyy")</td>
                        <td>
                            <a asp-action="MemberDetails" asp-route-memberId="@item.MemberId" class="btn btn-outline-success">Detaylar</a>
                        </td>
                        <td>
                            <form asp-controller="Admin" asp-action="MemeberDelete" method="post">
                                <input type="hidden" name="memberId" value="@item.MemberId">
                                <button class='btn btn-outline-danger'>Sil</button>
                            </form>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/NoteDetails.cshtml
@model NoteModel
@{
    ViewData["Title"] = "NoteDetails";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="col-md-12 mt-5 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Ders Notu Düzenle</h4>
            <p class="card-description">
            </p>
            <form asp-controller="Admin" asp-action="NoteDetails" method="post" enctype="multipart/form-data" class="forms-sample">
                <input name="NoteId" type="hidden" class="form-control" value="@Model.NoteId">
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input type="text" asp-for="Title" class="form-control" placeholder="Başlık"
                           required="Gerekli" data-validation-required-message="Lütfen Başlık Giriniz" />
                </div>

                <div class="form-group">
                    <label asp-for="Content"></label>
                    <textarea type="text" asp-for="Content" class="form-control" placeholder="Açıklama"
                              required="Gerekli" data-validation-required-message="Lütfen Açıklama Giriniz"></textarea>
                </div>

                <div class="form-group">
                    <input type="hidden" asp-for="NoteImgUrl" />
                    <img src="~/upload/img/@Model.NoteImgUrl" width="100" />
                    <input type="file" asp-for="NoteImgUrl" name="file" />
                </div>

                <div class="form-group">
                    <input type="hidden" asp-for="NotePdfUrl" />
                    <img src="~/upload/img/pdf.png" width="100" />
                    <input type="file" asp-for="NotePdfUrl" name="pdffile" />

                </div>

                <div class="form-group">
                    <label>Kategori</label>
                    @Html.DropDownListFor(x=>x.CategoryId,(List<SelectListItem>)ViewBag.categories, new {@class="form-control"})
                </div>
                <div class="form-group">
                    <div class="form-check">
                        @if (Model.IsApproved == true)
                        {
                            <label asp-for="IsApproved" class="form-check-label">
                                <input asp-for=IsApproved type="checkbox" checked class="form-check-input">Yayında
                            </label>
                        }
                        else
                        {
                            <label asp-for="IsApproved" class="form-check-label">
                                <input asp-for=IsApproved type="checkbox" class="form-check-input">Yayınla
                            </label>

                        }
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button class="btn btn-light">İptal</button>
            </form>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Admin/NoteList.cshtml
@model IEnumerable<Note>
@{
    ViewData["Title"] = "NoteList";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<h1 class="m-5 mt-5">Notlar</h1>

<div class="col-md-12">
    <div class="table-responsive mt-5 ">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th>Fotoğraf</th>
                    <th>Başlık</th>
                    <th>İçerik</th>
                    <th>Pdf Link</th>
                    <th>Yükleme-Güncelleme Tarihi</th>
                    <th>Not Durum</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><img src="~/upload/img/@item.NoteImgUrl" width="50" height="" /></td>
                        <td>@item.Title</td>
                        <td>@item.Content</td>
                        <td><a href="~/upload/pdf/@item.NotePdfUrl" target="_blank"><img src="~/upload/img/pdf.png" width="50" height="" /></a></td>
                        <td>@item.CreatDate.ToString("dd.MM.yyyy")</td>
                        <td>
                            @if (item.IsApproved == true)
                            {
                                <span class="badge badge-success">Yayında</span>
                            }
                            else if (item.IsApproved == false)
                            {
                                <span class="badge badge-danger"> Yayında değil</span>
                            }

                        </td>
                        <td>
                            <a asp-controller="Admin" asp-action="NoteDetails" asp-route-noteId="@item.NoteId" class="btn btn-outline-success">Detaylar</a>

                        </td>
                        <td>
                            <form asp-controller="Admin" asp-action="NoteDelete" method="post">
                                <input type="hidden" name="noteId" value="@item.NoteId">
                                <button class='btn btn-outline-danger'>Sil</button>
                            </form>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>