Notlarim/Notlarim.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Notlarim.Business.Abstract;
using Notlarim.Entities;
using Notlarim.WebUI.Models;
using System.Net.Mail;
using System.Net;
using MyBlog.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using static Azure.Core.HttpHeader;
using NuGet.Packaging.Signing;
using System.Text;

namespace Notlarim.WebUI.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        //Tüm İşleler Api Üzerinde Gerçekleştirilmektedir.

        private INoteService _noteService;
        private IMessageService _messageService;
        public HomeController(INoteService noteService, IMessageService messageService)
        {
            _noteService = noteService;
            _messageService = messageService;
        }

        public IActionResult About()
        {
            return View();
        }

        // İletişim Sayfası
        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }

        #region Web Api
        // Anasayfa da api üzerinden Notları Listelem
        public async Task<IActionResult> GetNoteFromRestApi()
        {
            var notes = new List<Note>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7034/api/homes"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    notes = JsonConvert.DeserializeObject<List<Note>>(apiResponse);
                }
            }
            return View(notes);
        }

        public async Task<IActionResult> GetNoteDetailFromRestApi(int noteId)
        {
            var note = new Note();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7034/api/homes/notedetails/{noteId}"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        note = JsonConvert.DeserializeObject<Note>(apiResponse);
                    }
                }
            }
            return View(note);
        }
        public async Task<IActionResult> GetCategoriesAndNotesFromRestApi(int categoryId)
        {
            var notes = new List<Note>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7034/api/homes/cat/{categoryId}"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        notes = JsonConvert.DeserializeObject<List<Note>>(apiResponse);
                    }
                }
            }
            return View(notes);
        }
        public async Task<IActionResult> MailSendFromRestApi(Messages model)
        {
            using (var httpClient = new HttpClient())
            {
                string apiUrl = "https://localhost:7034/api/homes/mailsend";
                var jsonContent = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(apiUrl, jsonContent))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        ViewBag.Succes = "teşekkürler Mailniz başarı bir şekilde gönderildi";
                    }
                    else
                    {
                        ViewBag.Error = "Mesaj Gönderilirken hata oluştu";
                        return View();
                    }
                }
            }
            return View();

        }
        public async Task<IActionResult> SearchFromRestApi(string search)
        {
            using (var httpClient = new HttpClient())
            {
                var apiUrl = $"https://localhost:7034/api/homes/search/{search}";
                var jsonContent = new StringContent(JsonConvert.SerializeObject(search), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(apiUrl, jsonContent))
                {
                    List<SearchNote> searches = new List<SearchNote>();
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    searches = JsonConvert.DeserializeObject<List<SearchNote>>(apiResponse);
                    return View("Result", searches);
                }
            
            }
            
        }
        #endregion






    }
}

Notlarim/Notlarim.WebUI/ViewComponents/Note/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Notlarim.Business.Abstract;

namespace Notlarim.WebUI.ViewComponents.Note
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _categoryService.GetAll();
            return View(model);
        }
    }
}

Notlarim/Notlarim.WebUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Notlarım - Hakkımızda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron jum-img mt-5">
    <div class="container p-5">
        <h1 class="display-4 jum-h1">Ders Notlarım</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">


        <h1>Merhaba ve Hoş Geldiniz!</h1>
        <p>Üniversite Ders Notları Paylaşım Sitemize hoş geldiniz. Amacımız, üniversite öğrencilerine derslerinde başarıya ulaşmalarına yardımcı olmak ve öğrenme süreçlerini kolaylaştırmaktır. Bu platform, öğrencilerin ders notlarını paylaşmalarını ve kapsamlı bir öğrenme kaynağı oluşturmalarını sağlamak için tasarlanmıştır.</p>

        <h2>Vizyonumuz</h2>
        <p>Vizyonumuz, eğitimin ve bilginin özgürce paylaşıldığı bir dünya yaratmaktır. Üniversite eğitimi, bir bireyin kariyeri ve hayatındaki başarı için temel taşlardan biridir. Bu nedenle, üniversite öğrencilerine en iyi eğitim ve öğrenme deneyimini sunmak, topluluk üyelerimizin karşılıklı olarak birbirinden öğrenmesini sağlamak ve bilgi paylaşımını teşvik etmek temel hedeflerimiz arasındadır.</p>

        <h2>Misyonumuz</h2>
        <p>Misyonumuz, öğrencilerin ders notlarını paylaşarak ve farklı ders materyallerini bir araya getirerek daha iyi bir öğrenme deneyimi yaşamalarına yardımcı olmaktır. Üniversite derslerinde başarılı olmak için sadece ders kitapları ve ders içerikleri yeterli olmayabilir. Pratik notlara, örnek ödevlere ve öğrenci yorumlarına erişim, öğrencilerin dersleri daha iyi anlamalarına ve öğrenme süreçlerini geliştirmelerine yardımcı olur.</p>

        <h2>Ne Sunuyoruz</h2>
        <ul>
            <li><strong>Ders Notları Paylaşımı:</strong> Sitemizde, farklı üniversitelerden öğrenciler tarafından paylaşılan ders notlarını bulabilirsiniz. Bu notlar, farklı derslerdeki konuları ve kavramları anlamak için değerli bir kaynaktır.</li>
            <li><strong>Örnek Ödevler ve Sorular:</strong> Sık sık derslerde ödevler ve sorularla karşılaşırız ve bazen bunları çözmekte zorlanabiliriz. Sitemizde, öğrencilerin önceden çözdüğü örnek ödevler ve soruları bulabilir ve kendi çalışmalarınıza yardımcı olacak ipuçları edinebilirsiniz.</li>
            <li><strong>Forum ve Topluluk Desteği:</strong> Topluluk üyelerimiz için bir forum sağlıyoruz. Bu platformda, dersler, öğrenme teknikleri ve genel üniversite yaşamı hakkında deneyimlerinizi ve sorularınızı paylaşabilir, diğer üyelerle etkileşimde bulunabilirsiniz.</li>
        </ul>

        <h2>Topluluğumuza Katılın</h2>
        <p>Sitemiz, üniversite öğrencileri ve eğitim tutkunları için güçlü bir topluluk oluşturmayı hedeflemektedir. Siz de ders notlarınızı paylaşabilir, öğrenme sürecinizde edindiğiniz değerli bilgileri diğer öğrencilerle paylaşabilirsiniz. Böylece, daha geniş bir öğrenme ağına katkıda bulunabilir ve birbirimizden öğrenmenin gücünü deneyimleyebiliriz.</p>

        <p>Teşekkür ederiz, çünkü topluluğumuzun bir parçası olarak, birlikte daha iyi bir öğrenme deneyimi oluşturuyoruz.</p>

        <p>Eğitim dolu günler dileriz!</p>

        <p><em>Üniversite Ders Notları Paylaşım Sitesi Ekibi</em></p>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Home/CategoriesAndNotes.cshtml
@model IEnumerable<Note>
@{
    ViewData["Title"] = "Notlarım - Kategori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-3">
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="pr-3">Kategoriler</span></h5>

            @await Component.InvokeAsync("CategoryList")

        </div>

        <div class="col-md-9 d-block">
            <div class="row pb-3">
                @if (Model.Count() == 0)
                {
                    <div class="col-md-9">
                        <div class="alert alert-info">Kategoriye Ait Ders Notu Bulunamadı</div>
                    </div>
                }
                else
                {
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4 text-center mt-3">
                            <a asp-action="NoteDetails" asp-route-noteId="@item.NoteId" class="text-dark link-dark"><img src="~/upload/img/@item.NoteImgUrl" width="210" height="100"> <br>@item.Title</a>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Home/Contact.cshtml
@using MyBlog.Entities.Concrete;
@model Messages
@{
    ViewData["Title"] = "Notlarım - İletişim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid m-5">
    <h2 class="position-relative text-uppercase"><span>Bize Ulaş</span></h2>
    <div class="row">
        <div class="col-lg-7 ">
            <div class="p-30">
                <div id="back" class="mb-2 text-center">
                    @if (ViewBag.Succes != null)
                    {
                        <h5 class="text-success">@ViewBag.Succes</h5>
                    }
                    @if (ViewBag.Error != null)
                    {
                        <h5 class="text-danger">@ViewBag.Error</h5>
                    }
                </div>
                <form asp-controller="Home" asp-action="Contact" method="post">
                    <div class="form-group">
                        <input asp-for="Name" type="text" class="form-control" placeholder="İsim"
                               required="required" data-validation-required-message="Lütfen İsim Giriniz" />

                    </div>
                    <div class="form-group">
                        <input asp-for="Email" type="email" class="form-control" placeholder="Email"
                               required="required" data-validation-required-message="Lütfen Email Adresiniz Giriniz" />

                    </div>
                    <div class="form-group">
                        <input asp-for="Title" type=" text" class="form-control" placeholder="Konu"
                               required="required" data-validation-required-message="Lütfen Konu Giriniz" />

                    </div>
                    <div class="form-group">
                        <textarea asp-for="Message" class=" form-control" rows="8" placeholder="Mesaj"
                                  required="required"
                                  data-validation-required-message="Lütfen Mesajınızı Giriniz">
                        </textarea>
                    </div>
                    <div>
                        <button class="btn btn-danger py-2 px-4" type="submit" id="sendMessageButton">
                            Mail Gönder
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="p-30 mb-30">
                <iframe style="width: 100%; height: 250px;"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48192.25415825653!2d29.063052999999996!3d40.981133!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac790b17ba89d%3A0xd2d24ea0437a7ee2!2zS2FkxLFrw7Z5L8Swc3RhbmJ1bA!5e0!3m2!1str!2str!4v1689948350464!5m2!1str!2str"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="mt-3 p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Kadıköy / İsatnbul</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>notlarim@gmail.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+90 534 345 67 89</p>
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Home/GetCategoriesAndNotesFromRestApi.cshtml
@model IEnumerable<Note>
@{
    ViewData["Title"] = "GetCategoriesAndNotesFromRestApi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-3">
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="pr-3">Kategoriler</span></h5>

            @await Component.InvokeAsync("CategoryList")

        </div>

        <div class="col-md-9 d-block">
            <div class="row pb-3">
                @if (Model.Count() == 0)
                {
                    <div class="col-md-9">
                        <div class="alert alert-info">Kategoriye Ait Ders Notu Bulunamadı</div>
                    </div>
                }
                else
                {
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4 text-center mt-3">
                            <a asp-action="GetNoteDetailFromRestApi" asp-route-noteId="@item.NoteId" class="text-dark link-dark"><img src="~/upload/img/@item.NoteImgUrl" width="210" height="100"> <br>@item.Title</a>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Home/GetNoteDetailFromRestApi.cshtml
@model Note
@{
    ViewData["Title"] = "GetNoteDetailFromRestApi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    bool isLoggedIn = Context.Session.GetString("usermail") != null;
}
<style>
    .blocked-link {
        pointer-events: none;
        cursor: default;
    }
</style>

<div class="row mt-5">
    <div class="col-md-12">
        <img src="~/upload/img/@Model.NoteImgUrl" width="1120" height="600px" alt="">
    </div>
</div>
<div class="row">
    <div class="col-md-12 mt-3">
        <span>@Model.CreatDate.ToString("dd.MM.yyyy") - <a asp-action="GetCategoriesAndNotesFromRestApi" asp-route-categoryId="@Model.CategoryId">@Model.Category.CategoryName</a> - @Model.Member.Name @Model.Member.SurName  </span>
        <h2>@Model.Title</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <p>@Model.Content</p>
    </div>
</div>
<div class="row">
    @if (isLoggedIn)
    {
        <div class="col-md-12">
            <a href="~/upload/pdf/@Model.NotePdfUrl" target="_blank">Notu İndir</a>
        </div>
    }
    else
    {
        <div class="col-md-12">
            <a href="~/Login/Login">Notu İndir</a>
        </div>
    }
</div>

Notlarim/Notlarim.WebUI/Views/Home/GetNoteFromRestApi.cshtml
@model IEnumerable<Note>
@{
    ViewData["Title"] = "GetNoteFromRestApi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron jum-img mt-5">
    <div class="container p-5 mt-5">
        <h1 class="display-4 jum-h1">Ücretsiz Üniversite Ders Notları</h1>
        <hr class="my-4">
        <p>Üniversite Ders Notları, Detaylı Konu Anlatımları ve Özetlerini sizlere sunuyoruz</p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-3 not-link mt-3 text-center">
                    <a asp-action="GetNoteDetailFromRestApi" asp-route-noteId="@item.NoteId" class="text-dark mt-3"><img src="~/upload/img/@item.NoteImgUrl" width="210" height="100"> <br>@item.Title</a>
                </div>
            }
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Home/MailSendFromRestApi.cshtml
@using MyBlog.Entities.Concrete;
@model Messages
@{
    ViewData["Title"] = "MailSendFromRestApi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid m-5">
    <h2 class="position-relative text-uppercase"><span>Bize Ulaş</span></h2>
    <div class="row">
        <div class="col-lg-7 ">
            <div class="p-30">
                <div id="back" class="mb-2 text-center">
                    @if (ViewBag.Succes != null)
                    {
                        <h5 class="text-success">@ViewBag.Succes</h5>
                    }
                    @if (ViewBag.Error != null)
                    {
                        <h5 class="text-danger">@ViewBag.Error</h5>
                    }
                </div>
                <form asp-controller="Home" asp-action="MailSendFromRestApi" method="post">
                    <div class="form-group">
                        <input asp-for="Name" type="text" class="form-control" placeholder="İsim"
                               required="required" data-validation-required-message="Lütfen İsim Giriniz" />

                    </div>
                    <div class="form-group">
                        <input asp-for="Email" type="email" class="form-control" placeholder="Email"
                               required="required" data-validation-required-message="Lütfen Email Adresiniz Giriniz" />

                    </div>
                    <div class="form-group">
                        <input asp-for="Title" type=" text" class="form-control" placeholder="Konu"
                               required="required" data-validation-required-message="Lütfen Konu Giriniz" />

                    </div>
                    <div class="form-group">
                        <textarea asp-for="Message" class=" form-control" rows="8" placeholder="Mesaj"
                                  required="required"
                                  data-validation-required-message="Lütfen Mesajınızı Giriniz">
                        </textarea>
                    </div>
                    <div>
                        <button class="btn btn-danger py-2 px-4" type="submit" id="sendMessageButton">
                            Mail Gönder
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="p-30 mb-30">
                <iframe style="width: 100%; height: 250px;"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48192.25415825653!2d29.063052999999996!3d40.981133!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac790b17ba89d%3A0xd2d24ea0437a7ee2!2zS2FkxLFrw7Z5L8Swc3RhbmJ1bA!5e0!3m2!1str!2str!4v1689948350464!5m2!1str!2str"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="mt-3 p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Kadıköy / İsatnbul</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>notlarim@gmail.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+90 534 345 67 89</p>
            </div>
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Home/NoteDetails.cshtml
@model Note
@{
    ViewData["Title"] = "NoteDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    bool isLoggedIn = Context.Session.GetString("usermail") != null;
}
<style>
    .blocked-link {
        pointer-events: none;
        cursor: default;
    }
</style>

<div class="row mt-5">
    <div class="col-md-12">
        <img src="~/upload/img/@Model.NoteImgUrl" width="1120" height="600px" alt="">
    </div>
</div>
<div class="row">
    <div class="col-md-12 mt-3">
        <span>@Model.CreatDate.ToString("dd.MM.yyyy") - <a asp-action="CategoriesAndNotes" asp-route-categoryId="@Model.CategoryId">@Model.Category.CategoryName</a> - @Model.Member.Name @Model.Member.SurName  </span>
        <h2>@Model.Title</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <p>@Model.Content</p>
    </div>
</div>
<div class="row">
    @if (isLoggedIn)
    {
        <div class="col-md-12">
            <a href="~/upload/pdf/@Model.NotePdfUrl" target="_blank">Notu İndir</a>
        </div>
    }
    else
    {
        <div class="col-md-12">
            <a href="~/Account/Login">Notu İndir</a>
        </div>
    }
</div>

Notlarim/Notlarim.WebUI/Views/Home/NoteList.cshtml
@model IEnumerable<Note>
@{
    ViewData["Title"] = "NoteList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron jum-img mt-5">
    <div class="container p-5 mt-5">
        <h1 class="display-4 jum-h1">Ücretsiz Üniversite Ders Notları</h1>
        <hr class="my-4">
        <p>Üniversite Ders Notları, Detaylı Konu Anlatımları ve Özetlerini sizlere sunuyoruz</p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-3 not-link mt-3 text-center">
                    <a asp-action="NoteDetails" asp-route-noteId="@item.NoteId" class="text-dark mt-3"><img src="~/upload/img/@item.NoteImgUrl" width="210" height="100"> <br>@item.Title</a>
                </div>
            }
        </div>
    </div>
</div>

Notlarim/Notlarim.WebUI/Views/Home/Result.cshtml
@model List<SearchNote>
@{
    ViewData["Title"] = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row mt-5">
    <div class="col-md-12">
        <div class="row">
            @if (Model.Count == 0)
            {  <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-warning">
                               Kayıt Bulunamadı
                            </div>
                        </div>
                    </div>
            }
            else
            {
                @foreach (var item in Model)
                {
                    <div class="col-md-3 not-link mt-3 text-center">
                        <a asp-controller="Home" asp-action="NoteDetails" asp-route-noteId="@item.SearchNoteId" class="text-dark mt-3"><img src="~/upload/img/@item.SearchNoteImg" width="210" height="100"> <br>@item.SearchNoteTitle</a>
                    </div>
                }
            }
        </div>
    </div>
</div>